Add an on-demand fake miner
kadena-io/chainweb-mining-client pull request #24
Opened 2023-03-09 16:28 UTC by edmundnoble

2023-03-09 22:26 UTC, jwiegley commented on chainweb-mining-client.cabal
> +        , warp >= 3.3
This is one of those moments in a review where I wonder if I'll just sit idly by and allow the addition of a space that breaks consistency to burn my soul in infinite anguish, or speak up and appear the fool for needing such things to rest peacefully.

2023-03-09 22:28 UTC, jwiegley commented
A lot of build warnings... Also, do we have any tests for this package, or is it just tested-by-use right now?

2023-03-17 17:19 UTC, edmundnoble commented
it's tested by use as far as I know, and warnings are not fatal.

2023-03-20 20:36 UTC, larskuhtz commented
Test are implemented in the test folder: https://github.com/kadena-io/chainweb-mining-client/tree/master/test

Test run as part of CI here: https://github.com/kadena-io/chainweb-mining-client/blob/ae6e108ab221157198026f1a4d11976591b4e6ee/.github/workflows/build-application.yml#L65

2023-03-20 20:40 UTC, larskuhtz commented
> A lot of build warnings... Also, do we have any tests for this package, or is it just tested-by-use right now?

Most build warnings are about unused symbols in the stratum implementation. The reason is that parts of that implementation are still considered work in progress. I guess we could silence them with an pragma in the respective module.

2023-03-21 00:45 UTC, larskuhtz requested changes

2023-03-21 00:45 UTC, larskuhtz commented on src/Worker/Fake/OnDemand.hs
> +            return ()
```suggestion
        Right _ -> writeLog logger L.Error "mining loop exited unexpectedly"
```

2023-03-21 00:45 UTC, larskuhtz commented on src/Worker/Fake/OnDemand.hs
> +            else resp notFound
This feels a bit like the wrong way around to me. I would expect that the client selects the chain and the server would block until a block on that chain is mined.

The `POST make-block` would take a query parameter `cid` (or possibly a list of chain ids) and put that into the shared variable. The worker would then mine blocks until it mined at least one block on each requested chain. Once done it would unblock the server thread which would issue the response.

2023-03-21 14:33 UTC, edmundnoble commented on main/Main.hs
> +    | FakeConstantDelayWorker
I agree and I think your idea is great.

2023-03-21 18:57 UTC, edmundnoble commented on main/Main.hs
> +    , _configOnDemandInterface = "*"
I think this doesn't work as well if you run the client in docker, because it has its own interface.

2023-03-21 19:28 UTC, larskuhtz commented on main/Main.hs
> +    , _configOnDemandInterface = "*"
Yeah, I think, it would be visible only in the container (which is kinda what it's supposed to do).

But, yeah, it may be more convenient to keep it on "*", since it has to be integrated with other services in any case.

2023-03-21 22:47 UTC, larskuhtz requested changes
Could you please add documentation for the new functionality (either README or a wiki page in the repo)?

You may also consider adding a few test cases, for instance, for the new endpoints, ensuring that the API matches expectations.

I also added a few more minor suggestions.

2023-03-21 22:47 UTC, larskuhtz commented on src/Worker/OnDemand.hs
> +import Control.Concurrent
```suggestion
```

2023-03-21 22:47 UTC, larskuhtz commented on src/Worker/OnDemand.hs
> +    done Nothing = Wai.responseLBS serviceUnavailable503 [] "not enough work to make a block"
```suggestion
```

2023-03-21 22:47 UTC, larskuhtz commented on src/Worker/OnDemand.hs
> +                \newGoals -> atomically $ modifyTVar' goalsRef (HashMap.unionWith (+) newGoals)
`newGoals` is the request body in JSON? What is the JSON format? My guess is `[[Number, Number]]`, which is I am not sure if it is intended. 

What about an object ala `{ "0" : 1, "12": 2}`?

I think, this would need documentation, in the code, but also in the README or a wiki page in the repository.

2023-03-21 22:47 UTC, larskuhtz commented on src/Worker/OnDemand.hs
> +                \newGoals -> atomically $ modifyTVar' goalsRef (HashMap.unionWith (+) newGoals)
I think, it could also make sense to add a short-cut route for mining just a single block on one chain. Maybe something like `/make-block?chain=0` or even allowing more than one chain with a syntax ala `/make-block?chain=0,9,19`. (some APIs also use the syntax `/make-block?chain=0&chain=9&chain=19`, I think, I've also seen `/make-block?chain[]=0&chain[]=9&chain[]=19`, but I like the comma delimited list most for simple numbers.)

2023-03-21 22:51 UTC, edmundnoble commented on src/Worker/OnDemand.hs
> +                \newGoals -> atomically $ modifyTVar' goalsRef (HashMap.unionWith (+) newGoals)
It's already like `{ "0" : 1, "12": 2 }`, at least that worked when I tested it. I can document the new modes yeah in the README or something.

2023-03-22 19:05 UTC, larskuhtz approved these changes

2023-03-22 19:05 UTC, merged